### PR TITLE
Update Prettier formatting for JS files + Aesthetic Markdown formatting for README.md

### PR DESCRIPTION
**Pull request by rudrakshkarpe**
- Contributing as part of Hacktoberfest 2022, Happy hacking!

### CODE REVIEW

**Comment by Miya25** [comment]
this looks bit weird

**Comment by MrKrishnaAgarwal** [comment]
conflicts

**Review by MrKrishnaAgarwal — CHANGES_REQUESTED** [review]
resolve conflicts please

**Comment by MrKrishnaAgarwal** [comment]
I think, you haven't responded till now and there are still conflicts in the PR, so closing the PR for now, feel free to reopen it.

**Comment by rudrakshkarpe** [comment]
I'm so sorry for responding late, I am having on going university exams. I'll resolve the conflicts asap and will try to contribute my best. I kindly request to reopen the PR

**Comment by MrKrishnaAgarwal** [comment]
> I'm so sorry for responding late, I am having on going university exams. I'll resolve the conflicts asap and will try to contribute my best. I kindly request to reopen the PR

No worries, I have reopened it, best of luck 👨‍💻

**Comment by rudrakshkarpe** [comment]
Thanks will raise a PR by tomorrow @MrKrishnaAgarwal

**Comment by MrKrishnaAgarwal** [comment]
> Thanks will raise a PR by tomorrow @MrKrishnaAgarwal 

Sure, please make a new pr instead.
Thanks 👨‍💻

**Comment by rudrakshkarpe** [comment]
Making a new PR would be the best option I guess thanks for the suggestion :)

**Comment by MrKrishnaAgarwal** [comment]
> Making a new PR would be the best option I guess thanks for the suggestion :)

Sure, make it soon
Can you do it till Tommorow or till 12th Oct?

**Pull request closed without merging**
